IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = 'DB_VIAJAVA')
CREATE DATABASE DB_VIAJAVA
GO

USE DB_VIAJAVA
GO

IF NOT EXISTS(SELECT * FROM sys.tables WHERE name = 'TB_USUARIOS')
BEGIN
CREATE TABLE TB_USUARIOS 
(
  ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  NOME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL UNIQUE,
  SENHA VARCHAR(50) NOT NULL,
  TELEFONE VARCHAR(20) NOT NULL UNIQUE,
  ATIVO BIT NOT NULL DEFAULT 1,
  DATA_CADASTRO DATETIME DEFAULT GETDATE(),

)
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TB_DOCUMENTOS')
BEGIN
CREATE TABLE TB_DOCUMENTOS 
(
  NUMERO_DOCUMENTO VARCHAR(20),
  USUARIO_ID UNIQUEIDENTIFIER NOT NULL,
  TIPO_DOCUMENTO VARCHAR(30) NOT NULL,
  FOREIGN KEY (USUARIO_ID) REFERENCES TB_USUARIOS(ID),

  PRIMARY KEY(NUMERO_DOCUMENTO),
  CHECK(TIPO_DOCUMENTO = 'CPF' OR TIPO_DOCUMENTO = 'PASSAPORTE')
)
END	
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TB_ROLES')
BEGIN
CREATE TABLE TB_ROLES 
(
  ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  USUARIO_ID UNIQUEIDENTIFIER NOT NULL,
  ROLE VARCHAR(50) NOT NULL DEFAULT 'CLIENTE',
  FOREIGN KEY (USUARIO_ID) REFERENCES TB_USUARIOS(ID),

  CHECK(UPPER(ROLE) = 'CLIENTE' OR UPPER(ROLE)  = 'ADMIN')
)
END
GO


IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TB_PACOTES')
BEGIN
CREATE TABLE TB_PACOTES 
(
  ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID() ,
  TITULO VARCHAR(100) NOT NULL,
  ORIGEM VARCHAR(100) NOT NULL,
  DESTINO VARCHAR(100) NOT NULL,
  DESCRICAO TEXT NOT NULL,
  IMAGEM_URL VARCHAR(255),
  VALOR DECIMAL(10,2) NOT NULL,
  LIMITE_VIAJANTES INT NOT NULL,
  DATA_INICIO DATE NOT NULL,
  DATA_FIM DATE NOT NULL,
  DISPONIVEL BIT DEFAULT 1,

  CHECK(VALOR > 0),
  CHECK(LIMITE_VIAJANTES > 0),
  CHECK(DATA_FIM > DATA_INICIO)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TB_RESERVAS')
BEGIN
CREATE TABLE TB_RESERVAS 
(
  ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID() ,
  USUARIO_ID UNIQUEIDENTIFIER NOT NULL,
  PACOTE_ID UNIQUEIDENTIFIER NOT NULL,
  VALOR_TOTAL DECIMAL(10,2) NOT NULL,
  DATA_RESERVA DATETIME DEFAULT GETDATE(),
  DATA_VIAGEM DATE NOT NULL,
  STATUS_RESERVA VARCHAR(50) DEFAULT 'PENDENTE',
  FOREIGN KEY (USUARIO_ID) REFERENCES TB_USUARIOS(ID),
  FOREIGN KEY (PACOTE_ID) REFERENCES TB_PACOTES(ID),

  CHECK(VALOR_TOTAL > 0),
  CHECK(DATA_VIAGEM > DATA_RESERVA),
  CHECK(UPPER(STATUS_RESERVA) IN ('PENDENTE', 'CONFIRMADO', 'RECUSADO', 'CANCELADO'))
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TB_PAGAMENTOS')
BEGIN
CREATE TABLE TB_PAGAMENTOS 
(
  ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
  RESERVA_ID UNIQUEIDENTIFIER NOT NULL UNIQUE, 
  METODO VARCHAR(50) NOT NULL,
  VALOR_PAGO DECIMAL(10,2) NOT NULL,
  DATA_PAGAMENTO DATETIME NOT NULL,
  STATUS_PAGAMENTO VARCHAR(50) NOT NULL DEFAULT 'PENDENTE',
  FOREIGN KEY (RESERVA_ID) REFERENCES TB_RESERVAS(ID),

  CHECK(UPPER(METODO) IN ('PIX', 'CARTAO', 'BOLETO')),
  CHECK(VALOR_PAGO > 0),
  CHECK(UPPER(STATUS_PAGAMENTO) IN ('PENDENTE','APROVADO', 'RECUSADO', 'ESTORNADO'))
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TB_VIAJANTES')
BEGIN
CREATE TABLE TB_VIAJANTES 
(
  ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
  RESERVA_ID UNIQUEIDENTIFIER NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  DOCUMENTO VARCHAR(20) NOT NULL,
  DATA_NASC DATETIME NOT NULL,
  FOREIGN KEY (RESERVA_ID) REFERENCES TB_RESERVAS(ID),

  CHECK(DATA_NASC < GETDATE())
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TB_AVALIACOES')
BEGIN
CREATE TABLE TB_AVALIACOES 
(
  ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
  RESERVA_ID UNIQUEIDENTIFIER NOT NULL,
  NOTA INT,
  COMENTARIO TEXT,
  DATA_AVALIACAO DATETIME DEFAULT GETDATE(),
  REMOVIDO BIT DEFAULT 0,
  FOREIGN KEY (RESERVA_ID) REFERENCES TB_RESERVAS(ID),

  CHECK(LEN(NOTA) >= 0 AND LEN(NOTA) <= 5),
)
END
GO



