USE DB_VIAJAVA
GO

--------------------------------------------------------------------

-- CRIAÇÃO DAS VIEWS DO DASHBOARD.
--------------------------------------------------------------------

-- CRIAÇÃO DE VIEW COM MÉTRICAS GERAIS.

CREATE VIEW vw_metricas_gerais AS 
SELECT 
    U.CLIENTES_ATIVOS,
    R.RESERVAS_CONFIRMADAS,
    R.FATURAMENTO_TOTAL,
    A.MEDIA_AVALIACOES,
    P.PACOTES_DISPONIVEIS
FROM
    (SELECT COUNT(*) AS CLIENTES_ATIVOS FROM TB_USUARIOS WHERE ATIVO = 1) U
CROSS JOIN
    (SELECT COUNT(*) AS RESERVAS_CONFIRMADAS, SUM(VALOR_TOTAL) AS FATURAMENTO_TOTAL FROM TB_RESERVAS WHERE STATUS_RESERVA = 'Confirmado') R
CROSS JOIN
    (SELECT AVG(NOTA) AS MEDIA_AVALIACOES FROM TB_AVALIACOES) A
CROSS JOIN
    (SELECT COUNT(*) AS PACOTES_DISPONIVEIS FROM TB_PACOTES WHERE DISPONIVEL = 1) P
GO

-- VIEW DE FATURAMENTO MENSAL

CREATE VIEW vw_faturamento_mensal AS
SELECT 
  YEAR(DATA_RESERVA) AS ANO,
  MONTH(DATA_RESERVA) AS MES,
  COUNT(ID) AS QUANTIDADE_RESERVAS,
  SUM(VALOR_TOTAL) AS FATURAMENTO
FROM TB_RESERVAS
WHERE STATUS_RESERVA = 'Confirmado'
GROUP BY YEAR(DATA_RESERVA), MONTH(DATA_RESERVA)

GO

-- CRIAÇÃO DE VIEW DOS DESTINOS MAIS POPULARES
CREATE VIEW vw_destinos_populares AS 
SELECT P.DESTINO, COUNT(R.ID) AS RESERVAS,
       SUM(R.VALOR_TOTAL) AS FATURAMENTO
FROM TB_PACOTES P
JOIN TB_RESERVAS R ON P.ID = R.PACOTE_ID
WHERE R.STATUS_RESERVA = 'Confirmado'
GROUP BY P.DESTINO

GO
