USE DB_VIAJAVA
GO

-- LISTA OS USUÁRIOS COM SUAS RESPECTIVAS ROLES.

SELECT * FROM TB_USUARIOS;
SELECT * FROM TB_ROLES;

SELECT	
	U.NOME AS NOME,
	U.EMAIL AS EMAIL,
	U.ATIVO AS ATIVO,
	CASE RL.ROLE 
		WHEN 'cliente' THEN 'CLIENTE'
		WHEN 'admin' THEN 'ADMIN' 
	END AS [USUÁRIO CARGO]
FROM 
	TB_USUARIOS U LEFT JOIN TB_ROLES RL 
ON  U.ID = RL.USUARIO_ID
GROUP BY NOME, EMAIL, ATIVO, RL.ROLE;

GO

-- Lista todos os usuários ativos
SELECT ID, NOME, EMAIL, TELEFONE 
FROM TB_USUARIOS 
WHERE ATIVO = 1
ORDER BY NOME;

GO

-- Pacotes disponíveis ordenados por valor
SELECT ID, TITULO, ORIGEM, DESTINO, VALOR, DATA_INICIO, DATA_FIM
FROM TB_PACOTES
WHERE DISPONIVEL = 1 AND DATA_INICIO > GETDATE()
ORDER BY VALOR;

GO

-- Reservas confirmadas
SELECT R.ID, U.NOME AS CLIENTE, P.TITULO AS PACOTE, 
       R.VALOR_TOTAL, R.DATA_VIAGEM, R.STATUS_RESERVA
FROM TB_RESERVAS R
JOIN TB_USUARIOS U ON R.USUARIO_ID = U.ID
JOIN TB_PACOTES P ON R.PACOTE_ID = P.ID
WHERE R.STATUS_RESERVA = 'CONFIRMADO'
ORDER BY R.DATA_VIAGEM;

GO
-----------------------------------------------------------------

-- Total de vendas por pacote
SELECT P.TITULO, COUNT(R.ID) AS [QUANTIDADE RESERVAS], 
       SUM(R.VALOR_TOTAL) AS TOTAL_VENDIDO
FROM TB_PACOTES P
LEFT JOIN TB_RESERVAS R ON P.ID = R.PACOTE_ID
GROUP BY P.TITULO
ORDER BY TOTAL_VENDIDO DESC;

GO

-- Média de avaliações por pacote
SELECT P.TITULO, AVG(A.NOTA) AS MEDIA_AVALIACOES, 
       COUNT(A.ID) AS QUANTIDADE_AVALIACOES
FROM TB_PACOTES P
LEFT JOIN TB_AVALIACOES A ON P.ID = A.RESERVA_ID
GROUP BY P.TITULO
ORDER BY MEDIA_AVALIACOES DESC;

GO

-- Pagamentos por método
SELECT METODO, COUNT(ID) AS QUANTIDADE, 
       SUM(VALOR_PAGO) AS TOTAL_RECEBIDO,
       AVG(VALOR_PAGO) AS MEDIA_PAGAMENTO
FROM TB_PAGAMENTOS
WHERE STATUS_PAGAMENTO = 'Aprovado'
GROUP BY METODO
ORDER BY TOTAL_RECEBIDO DESC;

GO
-------------------------
-- Pacotes mais populares (com mais reservas)
SELECT TOP 5 P.TITULO, COUNT(R.ID) AS TOTAL_RESERVAS
FROM TB_PACOTES P
JOIN TB_RESERVAS R ON P.ID = R.PACOTE_ID
GROUP BY P.TITULO
ORDER BY TOTAL_RESERVAS DESC;

GO
-- Clientes que mais gastaram
SELECT TOP 10 U.NOME, U.EMAIL, 
       COUNT(R.ID) AS QUANTIDADE_RESERVAS,
       SUM(R.VALOR_TOTAL) AS TOTAL_GASTO
FROM TB_USUARIOS U
JOIN TB_RESERVAS R ON U.ID = R.USUARIO_ID
GROUP BY U.NOME, U.EMAIL
ORDER BY TOTAL_GASTO DESC;

GO
-- Ocupação dos pacotes (reservas vs limite)
SELECT P.TITULO, P.LIMITE_VIAJANTES,
       COUNT(V.ID) AS VIAJANTES_CONFIRMADOS,
       (P.LIMITE_VIAJANTES - COUNT(V.ID)) AS VAGAS_RESTANTES
FROM TB_PACOTES P
JOIN TB_RESERVAS R ON P.ID = R.PACOTE_ID
JOIN TB_VIAJANTES V ON R.ID = V.RESERVA_ID
WHERE R.STATUS_RESERVA = 'CONFIRMADO'
GROUP BY P.TITULO, P.LIMITE_VIAJANTES
ORDER BY VAGAS_RESTANTES;

GO

---------------------------------

-- Pacotes com avaliação abaixo da média
SELECT P.TITULO, AVG(A.NOTA) AS MEDIA_AVALIACAO
FROM TB_PACOTES P
JOIN TB_AVALIACOES A ON P.ID = A.PACOTE_ID
GROUP BY P.TITULO
HAVING AVG(A.NOTA) < (SELECT AVG(NOTA) FROM TB_AVALIACOES)
ORDER BY MEDIA_AVALIACAO;

-- Clientes com reservas pendentes de pagamento
SELECT U.NOME, U.EMAIL, U.TELEFONE,
       R.ID AS RESERVA_ID, R.VALOR_TOTAL,
       (R.VALOR_TOTAL - ISNULL(SUM(P.VALOR_PAGO), 0)) AS SALDO_DEVEDOR
FROM TB_USUARIOS U
JOIN TB_RESERVAS R ON U.ID = R.USUARIO_ID
LEFT JOIN TB_PAGAMENTOS P ON R.ID = P.RESERVA_ID AND P.STATUS_PAGAMENTO = 'Aprovado'
WHERE R.STATUS_RESERVA = 'Pendente'
GROUP BY U.NOME, U.EMAIL, U.TELEFONE, R.ID, R.VALOR_TOTAL
HAVING (R.VALOR_TOTAL - ISNULL(SUM(P.VALOR_PAGO), 0) > 0)
ORDER BY SALDO_DEVEDOR DESC;

-- Pacotes com melhor custo-benefício (maior nota / menor preço)
SELECT P.TITULO, P.VALOR, AVG(A.NOTA) AS MEDIA_AVALIACAO,
       (AVG(A.NOTA)/P.VALOR) AS CUSTO_BENEFICIO
FROM TB_PACOTES P
JOIN TB_RESERVAS RS ON P.ID = RS.ID
JOIN TB_AVALIACOES A ON RS.ID = A.RESERVA_ID
GROUP BY P.TITULO, P.VALOR
ORDER BY CUSTO_BENEFICIO DESC;


GO


----------------------------

-- Métricas gerais para dashboard
SELECT 
  (SELECT COUNT(*) FROM TB_USUARIOS WHERE ATIVO = 1) AS CLIENTES_ATIVOS,
  (SELECT COUNT(*) FROM TB_RESERVAS WHERE STATUS_RESERVA = 'CONFIRMADO') AS RESERVAS_CONFIRMADAS,
  (SELECT SUM(VALOR_TOTAL) FROM TB_RESERVAS WHERE STATUS_RESERVA = 'CONFIRMADO') AS FATURAMENTO_TOTAL,
  (SELECT AVG(NOTA) FROM TB_AVALIACOES) AS MEDIA_AVALIACOES,
  (SELECT COUNT(*) FROM TB_PACOTES WHERE DISPONIVEL = 1) AS PACOTES_DISPONIVEIS;

GO

-- Faturamento mensal
SELECT 
  YEAR(DATA_RESERVA) AS ANO,
  MONTH(DATA_RESERVA) AS MES,
  COUNT(ID) AS QUANTIDADE_RESERVAS,
  SUM(VALOR_TOTAL) AS FATURAMENTO
FROM TB_RESERVAS
WHERE STATUS_RESERVA = 'CONFIRMADO'
GROUP BY YEAR(DATA_RESERVA), MONTH(DATA_RESERVA)
ORDER BY ANO, MES;

-- Destinos mais populares
SELECT P.DESTINO, COUNT(R.ID) AS RESERVAS,
       SUM(R.VALOR_TOTAL) AS FATURAMENTO
FROM TB_PACOTES P
JOIN TB_RESERVAS R ON P.ID = R.PACOTE_ID
WHERE R.STATUS_RESERVA = 'CONFIRMADO'
GROUP BY P.DESTINO
ORDER BY RESERVAS DESC;
