USE DB_VIAJAVA;
GO

-- Índice para TB_USUARIOS
IF OBJECT_ID('dbo.TB_USUARIOS', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IDX_USUARIO_EMAIL')
        CREATE INDEX IDX_USUARIO_EMAIL ON dbo.TB_USUARIOS(EMAIL);
END

-- Índice para TB_DOCUMENTOS
IF OBJECT_ID('dbo.TB_DOCUMENTOS', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IDX_DOCUMENTO_NUMERO_DOCUMENTO')
        CREATE INDEX IDX_DOCUMENTO_NUMERO_DOCUMENTO ON dbo.TB_DOCUMENTOS(NUMERO_DOCUMENTO);
END


