USE DB_VIAJAVA;
GO

-- Índice para TB_USERS
IF OBJECT_ID('dbo.TB_USERS', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IDX_USER_EMAIL')
        CREATE INDEX IDX_USER_EMAIL ON dbo.TB_USERS(EMAIL);
END

-- Índice para TB_DOCUMENTS
IF OBJECT_ID('dbo.TB_DOCUMENTS', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IDX_DOCUMENT_NUMBER_DOCUMENT')
        CREATE INDEX IDX_DOCUMENT_NUMBER_DOCUMENT ON dbo.TB_DOCUMENTS(DOCUMENT_NUMBER);
END

IF OBJECT_ID('dbo.TB_PAYMENTS', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS(SELECT * FROM sys.indexes WHERE name = 'IDX_BOOKING_ORDER_NUMBER')
        CREATE INDEX IDX_BOOKING_ORDER_NUMBER ON dbo.TB_BOOKINGS(ORDER_NUMBER)
END